baseURL: "https://www.jannikarndt.de/"
title: "Jannik Arndt"
pagination:
  pagerSize: 50
theme: PaperMod
defaultContentLanguage: en
languages:
  en:
    languageCode: en
    languageDirection: ltr
    languageName: English
    weight: 1
    
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pluralizeListTitles: false
disableHugoGeneratorInject: false

minify:
  disableCSS: true
  disableHTML: true
  disableJS: true
  disableXML: true
  minifyOutput: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

server:
  headers:
    - for: /**
      values:
        Content-Security-Policy: "default-src 'self' http://localhost:1313 ws://localhost:1313/livereload; script-src 'self' 'sha256-pYERp1GFTQcj76yK8huGHJtriZpv9dsW7AdV7O+VrcQ=' 'sha256-JVVDOwRpMQvCZqoDwpZ1OUJ81UoJpBxumeEHC89A9PU=' 'sha256-RK7LdSEhpwvmYMT+Jix2uBLUXxlWBpHbN6lasgC6hv8='; style-src 'self';"
        Referrer-Policy: strict-origin-when-cross-origin
        X-Content-Type-Options: nosniff
        X-Frame-Options: DENY
        X-XSS-Protection: "1; mode=block"

params:
  env: production  # to enable Google Analytics, opengraph, twitter-cards and schema.
  title: "Jannik Arndt"
  description: "Scala-Dev, Swift-Hacker, Product-Junkie from Hamburg"
  author: "Jannik Arndt"  # author: ["Me", "You"] for multiple authors
  images:
    - "jannik.jpg"
  disableFingerprinting: false
  social: true
  hideLangSwitch: true
  hideFooter: true
  defaultTheme: auto  # dark, light, or auto
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false  # prev/next links at bottom
  ShowBreadCrumbs: true
  disableScrollToTop: true
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false
  ShowCodeCopyButtons: false # adds inline js, not allowed in content policy
  ShowAllPagesInArchive: true # no changes

  assets:
    disableScrollBarStyle: true
    favicon: "favicon.ico"
    favicon16x16: "favicons/favicon-16x16.png"
    favicon32x32: "favicons/favicon-32x32.png"
    apple_touch_icon: "favicons/apple-touch-icon.png"
    safari_pinned_tab: "favicons/apple-touch-icon.png"
    theme_color: "#576175"

  label:
    text: "JannikArndt.de"
    icon: "/favicons/apple-touch-icon.png"
    iconHeight: 35

  # home-info mode configuration
  homeInfoParams:
    Title: "Jannik Arndt"
    Content: "Scala-Dev, Swift-Hacker, Product-Junkie from Hamburg"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/JannikArndt"
    - name: github
      url: "https://github.com/JannikArndt"
    - name: linkedin
      url: "https://www.linkedin.com/in/jannikarndt"
    - name: xing
      url: "https://www.xing.com/profile/Jannik_Arndt"
    - name: email
      url: "mailto:jannik@jannikarndt.de"
    - name: cv
      url: "/cv.pdf"

  cover:
    hidden: true         # hide cover image everywhere except in structured data
    hiddenInList: true     # hide on list pages and home
    hiddenInSingle: true   # hide on single pages

  # Fuse.js search options
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - "title"
      - "permalink"
      - "summary"
      - "content"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: about
      name: "about"
      url: "about/"
      weight: 5
    - name: "blog"
      url: "archive/"
      weight: 10
    - name: "search"
      url: "search/"
      weight: 15
    - identifier: tags
      name: "tags"
      url: "tags/"
      weight: 10

pygmentsUseClasses: true
