baseurl = "https://www.jannikarndt.de"
languageCode = "en-us"
title = "Jannik Arndt"
theme = "hugo-creative-theme"
disableHugoGeneratorInject = "true"

[params]
	name = "Jannik Arndt"
	description = "Data Engineer, Software Developer & Musician from Hamburg, Germany"
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "jannikarndt.de"

		[params.navigation.links]
			about        = "About"
			services     = "Software"
			publications = "Publications"
            blog         = "Blog"
			contact      = "Contact"

	# About section
	[params.about]
		headline    = "About"
        mbti = "ENTJ"

        [[params.about.steps]]
            from = "1989"
            to   = ""
            step = "Löptin"
            link = "https://de.wikipedia.org/wiki/Löptin"

        [[params.about.steps]]
            from = "1999"
            to   = "2008"
            step = "Preetz"
            link = "https://www.fsg-preetz.de"

        [[params.about.steps]]
            from = "2008"
            to   = "2015"
            step = "Oldenburg"
            link = "https://www.uni-oldenburg.de"

        [[params.about.steps]]
            from = "2015"
            to   = "2016"
            step = "PPI, Hamburg"
            link = "https://www.ppi.de"

        [[params.about.steps]]
            from = "2017"
            to   = "today"
            step = "Holisticon, Hamburg"
            link = "https://www.holisticon.de"

	# Service section
	[params.services]
		headline = "Software"

        [[params.services.list]]
            icon = "https://jannikarndt.github.io/Canal/bridge.png"
            title = "Canal"
            description = "A free and open-source COBOL editor and analysis tool"
            link = "https://jannikarndt.github.io/Canal/"

        [[params.services.list]]
			icon = "https://jannikarndt.github.io/Musicista/icon.png"
			title = "Musicista"
			description = "A free and open-source framework for computational musicology"
            link = "https://jannikarndt.github.io/Musicista/"

		[[params.services.list]]
            icon = "https://github.com/JannikArndt/DataMover/raw/master/Resources/logo.png"
            title = "DataMover"
            description = "Out of the box scheduling, logging, monitoring and data governance for your scala ETL jobs"
            link = "https://github.com/JannikArndt/DataMover"

        [[params.services.list]]
            icon = "https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png"
            title = "More"
            description = "Show Github Repositories"
            link = "https://github.com/JannikArndt?tab=repositories"

    # Blog section
	[params.blog]
		headline = "Blog"

    # Publications section
    [params.publications]
        headline = "Publications"

        [[params.publications.years]]
            year = "2014"

            [[params.publications.years.entry]]
                text = "Jannik Arndt: “Musicista — A Framework for Computational Musicology”. Masterarbeit,  2014."
                link = "https://www.jannikarndt.de/publications/Jannik%20Arndt%20-%20Musicista.pdf"
                website = "https://jannikarndt.github.io/Musicista/"

            [[params.publications.years.entry]]
                text = "Jannik Arndt: “Erkennung von Motiv- und Themenvariationen”, in Gesellschaft für Informatik (Hrsg.): *Informatiktage 2014*, LNI S-13, Potsdam, 2014 (ISBN 978-3-88579-447-9)"
                link = "https://www.jannikarndt.de/publications/Variationsfindung/Erkennung%20von%20Motiv-%20und%20Themenvariationen.pdf"
            
            [[params.publications.years.entry]]
                text = "Jannik Arndt, Thomas Meents, Bernd Nottbeck: “Multidimensional Process Mining mit dem Process Cube Explorer”, in Gesellschaft für Informatik (Hrsg.): *Informatiktage 2014*, LNI S-13, Potsdam, 2014 (ISBN 978-3-88579-447-9)"
                link = "https://www.jannikarndt.de/publications/Multidimensional%20Process%20Mining%20mit%20dem%20Process%20Cube%20Explorer.pdf"

        [[params.publications.years]]
            year = "2013"

            [[params.publications.years.entry]]
                text = "Jannik Arndt: “Genetic Mining und Heuristic Mining”. 2013."
                link = "https://www.jannikarndt.de/publications/Genetic%20Mining%20und%20Heuristic%20Mining.pdf"

            [[params.publications.years.entry]]
                text = "Ira Diethelm, Jannik Arndt, Malte Dünnebier, Jörn Syrbe: “Informatics in Schools: Local Proceedings of the 6th International Conference ISSEP 2013 - Selected Papers”, *Commentarii informaticae didacticae*, Universitätsverlag Potsdam, 2013."
                link = "http://opus.kobv.de/ubp/volltexte/2013/6368/"

        [[params.publications.years]]
            year = "2012"

            [[params.publications.years.entry]]
                text = "Jannik Arndt: “Forderungen an ein Datenmodell für Rekombination als Ansatz für Künstliche Kreativität”, in Proc. *3rd IEEE Germany Student Conference*, Passau, 2012."
                link = "https://www.jannikarndt.de/publications/Forderungen%20an%20ein%20Datenmodell.pdf"

            [[params.publications.years.entry]]
                text = "Jannik Arndt: “Rekombination — Einführung in die Künstliche Kreativität”. Bachelorarbeit, 2012."
                link = "https://www.jannikarndt.de/publications/Rekombination/Jannik%20Arndt%20-%20Rekombination.pdf"
                website = "http://www.student.uni-oldenburg.de/jannik.arndt/ekk.html"

        [[params.publications.years]]
            year = "misc"

            [[params.publications.years.entry]]
                text = "Einführung in LaTeX"
                link = "https://www.jannikarndt.de/publications/Einf%C3%BChrung%20in%20LaTeX.pdf"

	# Contact section
	[params.contact]
        github = "https://github.com/JannikArndt"
        twitter = "https://twitter.com/JannikArndt"
        facebook = "https://www.facebook.com/jannik.arndt"
        linkedin = "https://www.linkedin.com/in/jannikarndt"
        xing = "https://www.xing.com/profile/Jannik_Arndt"
		email = "jannik@jannikarndt.de"