baseurl = "https://www.jannikarndt.de"
languageCode = "en-us"
title = "Jannik Arndt"
theme = "jannikarndt"
disableHugoGeneratorInject = "true"

[params]
	name = "Jannik Arndt"
	description = "Data Engineer, Software Developer & Musician from Hamburg, Germany"
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "jannikarndt.de"

		[params.navigation.links]
			about        = "About"
            blog         = "Blog"
			contact      = "Contact"

	# About section
	[params.about]
		headline    = "About"
        mbti = "ENTJ"

        [[params.about.steps]]
            from = "1989"
            to   = ""
            step = "Löptin"
            link = "https://de.wikipedia.org/wiki/Löptin"

        [[params.about.steps]]
            from = "1999"
            to   = "2008"
            step = "Preetz"
            link = "https://www.fsg-preetz.de"

        [[params.about.steps]]
            from = "2008"
            to   = "2015"
            step = "Oldenburg"
            link = "https://www.uni-oldenburg.de"

        [[params.about.steps]]
            from = "2015"
            to   = "2016"
            step = "PPI, Hamburg"
            link = "https://www.ppi.de"

        [[params.about.steps]]
            from = "2017"
            to   = "2019"
            step = "Holisticon, Hamburg"
            link = "https://www.holisticon.de"

        [[params.about.steps]]
            from = "2019"
            to   = "today"
            step = "MOIA, Hamburg"
            link = "https://www.moia.io"

    # Blog section
	[params.blog]
		headline = "Blog"

	# Contact section
	[params.contact]
        github = "https://github.com/JannikArndt"
        twitter = "https://twitter.com/JannikArndt"
        facebook = "https://www.facebook.com/jannik.arndt"
        linkedin = "https://www.linkedin.com/in/jannikarndt"
        xing = "https://www.xing.com/profile/Jannik_Arndt"
		email = "jannik@jannikarndt.de"