template: opengraph/template.png
title:
  start:
    px: 100
    py: 172
  fgHexColor: "#7B8EA6"
  fontSize: 72
  fontStyle: Bold
  maxWidth: 700
  lineSpacing: 10
category:
  start:
    px: 20
    py: 100
  fgHexColor: "#E5B52A"
  fontSize: 42
  fontStyle: Regular
info:
  start:
    px: 100
    py: 120
  fgHexColor: "#A0A0A0"
  fontSize: 38
  fontStyle: Regular
  separator: " — "
tags:
  start:
    px: 120
    py: -475
  fgHexColor: "#FFFFFF"
  bgHexColor: "#7F7776"
  fontSize: 22
  fontStyle: Medium
  boxAlign: Left
  boxSpacing: 6
  boxPadding:
    top: 6
    right: 10
    bottom: 6
    left: 8
